# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "文档"
  pageRef = "docs"
  weight = 10

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 100

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://twitter.com/burufugu"
  weight = 200

#[[main]]
#  identifier = "mastodon"
#  pre = "mastodon"
#  weight = 300
#  url = "https://masto.ai/@blowfish"

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/nunocoracao/blowfish"
  weight = 400


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "关于"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "联系"
   pageRef = "authors"
   weight = 20

 [[footer]]
   name = "RSS"
   pageRef = "tags"
   weight = 30

 [[footer]]
   name = "请喝咖啡"
   pageRef = "authors"
   weight = 40