# -- 主题选项 --
# 这些选项控制主题的功能，并允许您
# 自定义网站的显示效果。
#
# 有关每个参数的详细信息，请参阅主题文档。
# https://blowfish.page/docs/configuration/#theme-parameters

# 配色方案，https://blowfish.page/zh-cn/docs/getting-started/#avocado
colorScheme = "blowfish"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = false # 主题外观是否根据访问者操作系统的偏好自动切换。设置为 false 会强制网站始终使用 defaultAppearance

enableA11y = false # 是否启用无障碍切换按钮
enableSearch = true # 是否开启网站的搜索功能，设为 true 即为启用。注意，搜索功能依赖于站点设置中的 outputs.home 设置，请确保此值配置正确

# 是否可以将<code>代码块复制到剪贴板。想要使用代码复制功能，需要将 highlight.noClasses 参数设置为 false
enableCodeCopy = true

# 是否在发布后启用“通过邮件回复”的链接
replyByEmail = false

# 指定最近文章中应该展示的模块。 如果没有指定，则使用文章数量最多的板块
# mainSections = ["section1", "section2"]

# 用于支持搜索引擎爬虫如何处理你的网站。如果设置了该值，它将被输出在页面头部。具体的参数值请参考 Google 文档
# robots = ""

disableImageOptimization = false # 禁用图片上所有图片的调整大小和优化功能，使用 Markdown 语法插入的图片（![](image.jpg)）除外
disableImageOptimizationMD = false # 所有以 Markdown 语法（![](image.jpg)）插入的图片，禁用其调整大小和优化功能
disableTextInHeader = false # 宽度（以像素为单位）用于缩放背景图像
# backgroundImageWidth = 1200

defaultBackgroundImage = "img/ocean.jpg" # 设置默认背景图，用于 background 和 hero 布局下的主页
#defaultFeaturedImage = "img/my-bgimg.jpg" # 设置默认背景图片，用于所有文章的featured图片，可以通过文章目录中的 featured 图片替换
# defaultSocialImage = "/android-chrome-512x512.png" # 社交媒体分享（Open Graph 和 Twitter）使用的默认图片，可以通过文章目录中的 featured 图片替换
hotlinkFeatureImage = false # 在文章特色图片和文章卡片中外链图片。这些图片不会被 Hugo 处理
# imagePosition = "50% 50%" # 使用 object-position 属性设置默认图像的位置

# 当菜单被选择时，标记主菜单中的菜单项
highlightCurrentMenuArea = true

# 开启智能目录，视图中的项目将会被高亮显示
smartTOC = true
# 当开启智能目录，如果目录级别不再被聚焦时，将会隐藏更深层次的目录
# smartTOCHideUnfocusedChildren = true

# CSS/JS文件指纹的哈希算法，防止浏览器缓存问题
fingerprintAlgorithm = "sha512" # Valid values are "sha512" (default), "sha384", "sha256"

giteaDefaultServer = "https://git.fsfe.org" # 短代码 gitea 的默认 server 参数
forgejoDefaultServer = "https://v11.next.forgejo.org" # 短代码 forgejo 的默认 server 参数

# 定义整个站点的页头的布局，支持的参数有 basic、fixed、fixed-fill、and fixed-fill-blur.
[header]
  # layout = "basic"
  # layout = "fixed"
  # layout = "fixed-fill"
  # layout = "fixed-gradient"
  layout = "fixed-fill-blur" # 透明 + 毛玻璃模糊效果

[footer]
  showMenu = true # 显示/隐藏页面底部菜单
  showCopyright = true # 是否在底部显示 copyright 版权信息
  showThemeAttribution = true # 是否在网站底部中显示"powered by" 的主题归属信息。如果禁用此参数，请考虑在你网站的其他位置设置主题归属信息，例如在关于页面
  showAppearanceSwitcher = true # 是否在也页面底部显示外观切换器。浏览器的本地存储会缓存访问者的偏好设置
  showScrollToTop = true # 当设置为 true 时，显示返回顶部的箭头按钮
  links = [
    { title = "Blogs Club", url = "https://www.blogsclub.org/blog/45.html" },
    { title = "虫洞", url = "https://foreverblog.cn/go.html" },
    { title = "十年之约", url = "https://www.foreverblog.cn/blog/6529.html" },
    { title = "萌ICP备20250188号", url = "https://icp.gov.moe/?keyword=mgrowup.com" }
  ]

# 主页布局
[homepage]
  layout = "background" # 首页布局参数。合法的参数值有： page、profile、hero、card、background 或 custom
  #homepageImage = "" # 在 hero 和 card 布局中使用的图像。图片可以来自于本地的资源目录，也可以是外部图像 URL
  showRecent = true # 是否在主页展示最新文章列表
  showRecentItems = 5 # 如果将 showRecent 设置为 true，此参数用于显示多少篇文章。如果没有设置或者为0，则默认显示5篇文章
  showMoreLink = true # 是否在主页底部添加“显示更多”，该链接会降会用带到一个预定义位置
  showMoreLinkDest = "/posts/" # 更多按钮所指向的位置
  cardView = true # 将列表展示为卡片容器
  cardViewScreenWidth = false # 增强列表中卡片的宽度，使其可以占据可用的全部宽度
  layoutBackgroundBlur = true # 向下滚动主页时，是否模糊背景图
  disableHeroImageFilter = false # 主页背景是否套用图片滤镜

[article]
  showDate = true
  showViews = false # # 是否显示文章和列表页面的阅读量。这需要集成 firebase
  showLikes = false # 是否显示文章和列表页面的点赞量。这需要集成 firebase
  showDateOnlyInArticle = false # 是否在文章内显示日期，不影响文章列表或卡片页面的日期显示
  showDateUpdated = false # 是否展示文章的更新日期
  showAuthor = false # 是否在文章底部显示作者框
  showAuthorBottom = false # 作者框显示在每页的底部而不是顶部
  showHero = true # 文章缩略图/头图
  heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # 向下滚动主页时，是否模糊背景图
  layoutBackgroundHeaderSpace = false # 在标题和正文之间添加空白区域间隔
  showBreadcrumbs = false # 是否在文章或列表页面显示面包屑导航
  showDraftLabel = true # 当使用 --buildDrafts 构建网站时，是否在文章旁边显示草稿
  showEdit = false # 是否展示编辑文章的链接
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true # 当激活 article.showEdit 参数，是否将文章的路径附加到 article.editURL 参数所设置的 URL 后面
  seriesOpened = true # 是否打开系列模块
  showHeadingAnchors = true # 是否在文章的标题旁显示锚点链接
  showPagination = true # 是否在文章页脚显示下一篇/上一篇链接  
  invertPagination = false # 是否翻转下一篇/上一篇的链接方向  
  showReadingTime = false # 是否显示文章的预估阅读时间
  showTableOfContents = true # 是否显示文章目录
  # showRelatedContent = false # 为文章显示相关内容。如果你想要启用此功能，请检查 hugo.toml 文件并复制所有 related 相关的参数，如果你想自定义，也可以对 hugo.toml 添加额外配置。更多内容请参考 Hugo 文档 中关于 related 的内容
  # relatedContentLimit = 3 # 如果启用showRelatedContent，则限制显示相关文章的数量
  showTaxonomies = false # 是否显示文章的分类或标签信息
  showCategoryOnly = true # use showTaxonomies OR showCategoryOnly, not both
  showAuthorsBadges = true # 是否在文章作者旁显示徽章
  showShareButtons = true # 是否显示文章分享按钮
  showWordCount = false # 是否显示文章字数统计
  # sharingLinks = [ "linkedin", "twitter", "bluesky", "mastodon", "reddit", "pinterest", "facebook", "email", "whatsapp", "telegram", "line"]
  showZenMode = true #指定是否激活文章阅读的禅模式，即隐藏常规的界面元素
  # 如下是自定义的参数
  showDonate = true # 默认显示文章底部的"请喝咖啡"
  showDocInfo= true # 默认显示文章底部的"文档信息"
  licenseLink = "https://creativecommons.org/licenses/by-nc/4.0/" # 版权信息
  licenseName = "CC BY-NC 4.0" # 版权信息

# 文章页
[list]
  showHero = true
  heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false # 是否在标题栏显示面包屑导航
  showSummary = true # 是否在列表页显示文章摘要。如果在扉页参数中没有提供摘要，那么将会使用站点配置 中的 summaryLength 参数自动生成一个
  showTableOfContents = true # 是否在文章中显示目录表
  showCards = false # 是否将每个文章显示为卡片或简单的内联文本
  orderByWeight = false # 是否按照权重（weights）排序文章
  groupByYear = true # 是否根据年做聚合
  cardView = false # 将列表展示为卡片容器
  cardViewScreenWidth = false # 增强列表中卡片的宽度，使其可以占据可用的全部宽度
  constrainItemsWidth = false # 将项目宽度限制为 prose 以提高可读性。在没有 feature 图片的时候非常有用
  showViews = false # 需要配合firebase使用
  showLikes = false # 需要配合firebase使用

# 网站地图
[sitemap]
  excludedKinds = ["taxonomy", "term"]

# 分类法
[taxonomy]
  showTermCount = true # 是否在分类列表总显示对应的数量
  showHero = true # 缩略图是否会在每个页面中作为 hero 图像显示
  heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false # 是否在标题栏显示面包屑导航
  showViews = false # 是否显示文章阅读量。这需要集成 firebase
  showLikes = false
  showTableOfContents = false # 是否显示目录
  cardView = false # 将列表展示为卡片容器

# 术语/词语/措辞
[term]
  showHero = true
  heroStyle = "thumbAndBackground"
  showBreadcrumbs = false # 是否在标题栏显示面包屑导航
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false
