# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

# 配色方案，https://blowfish.page/zh-cn/docs/getting-started/#avocado
colorScheme = "Blowfish"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = false

enableA11y = false # 是否启用无障碍切换按钮
enableSearch = true # 是否开启网站的搜索功能，设为 true 即为启用。注意，搜索功能依赖于站点设置中的 outputs.home 设置，请确保此值配置正确

# 是否可以将<code>代码块复制到剪贴板。想要使用代码复制功能，需要将 highlight.noClasses 参数设置为 false
enableCodeCopy = false

# 是否在发布后启用“通过邮件回复”的链接
replyByEmail = false 

# 指定最近文章中应该展示的模块。 如果没有指定，则使用文章数量最多的板块
# mainSections = ["section1", "section2"]

# 用于支持搜索引擎爬虫如何处理你的网站。如果设置了该值，它将被输出在页面头部。具体的参数值请参考 Google 文档
# robots = ""

disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
# backgroundImageWidth = 1200

defaultBackgroundImage = "img/bluebg.png" # 设置默认背景图，用于 background 和 hero 布局下的主页
# defaultFeaturedImage = "IMAGE.jpg" # used as default for featured images in all articles
# defaultSocialImage = "/android-chrome-512x512.png" # used as default for social media sharing (Open Graph and Twitter)
hotlinkFeatureImage = false
# imagePosition = "50% 50%"

# 当菜单被选择时，标记主菜单中的菜单项
# highlightCurrentMenuArea = true

# 开启智能目录，视图中的项目将会被高亮显示
smartTOC = true
# 当开启智能目录，如果目录级别不再被聚焦时，将会隐藏更深层次的目录
# smartTOCHideUnfocusedChildren = true

# CSS/JS文件指纹的哈希算法，防止浏览器缓存问题
fingerprintAlgorithm = "sha512" # Valid values are "sha512" (default), "sha384", "sha256"

giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v11.next.forgejo.org"

# 定义整个站点的页头的布局，支持的参数有 basic、fixed、fixed-fill、and fixed-fill-blur.
[header]
  layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
  showMenu = true # 显示/隐藏页面底部菜单
  showCopyright = true # 是否在底部显示 copyright 版权信息
  showThemeAttribution = true # 是否在网站底部中显示"powered by" 的主题归属信息。如果禁用此参数，请考虑在你网站的其他位置设置主题归属信息，例如在关于页面
  showAppearanceSwitcher = true # 是否在也页面底部显示外观切换器。浏览器的本地存储会缓存访问者的偏好设置
  showScrollToTop = true # 当设置为 true 时，显示返回顶部的箭头按钮
  links = [
    { title = "Blogs Club", url = "https://www.blogsclub.org/blog/45.html" },
    { title = "虫洞", url = "https://foreverblog.cn/go.html" },
    { title = "十年之约", url = "https://www.foreverblog.cn/blog/6529.html" },
    { title = "萌ICP备20250188号", url = "https://icp.gov.moe/?keyword=mgrowup.com" }
  ]

# 主页布局
[homepage]
  layout = "background" # 首页布局参数。合法的参数值有： page、profile、hero、card、background 或 custom
  #homepageImage = "" # 在 hero 和 card 布局中使用的图像。图片可以来自于本地的资源目录，也可以是外部图像 URL
  showRecent = true # 是否在主页展示最新文章列表
  showRecentItems = 5 # 如果将 showRecent 设置为 true，此参数用于显示多少篇文章。如果没有设置或者为0，则默认显示5篇文章
  showMoreLink = true # 是否在主页底部添加“显示更多”，该链接会降会用带到一个预定义位置
  showMoreLinkDest = "/posts/" # 更多按钮所指向的位置
  cardView = true # 将列表展示为卡片容器
  cardViewScreenWidth = false # 增强列表中卡片的宽度，使其可以占据可用的全部宽度
  layoutBackgroundBlur = false # 向下滚动主页时，是否模糊背景图
  disableHeroImageFilter = false # 主页背景是否套用图片滤镜

[article]
  showDate = true
  showViews = false # # 是否显示文章和列表页面的阅读量。这需要集成 firebase
  showLikes = false # 是否显示文章和列表页面的点赞量。这需要集成 firebase
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = true
  showAuthorBottom = false
  showHero = false
  # heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = false # 向下滚动主页时，是否模糊背景图
  layoutBackgroundHeaderSpace = false # 在标题和正文之间添加空白区域间隔
  showBreadcrumbs = false # 是否在文章或列表页面显示面包屑导航
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  seriesOpened = false # 是否打开系列模块
  showHeadingAnchors = true  
  showPagination = true # 是否在文章页脚显示下一篇/上一篇链接  
  invertPagination = false # 是否翻转下一篇/上一篇的链接方向  
  showReadingTime = true # 是否显示文章的预估阅读时间
  showTableOfContents = true
  # showRelatedContent = false
  # relatedContentLimit = 3

  # 是否显示文章关联的分类/标签
  showTaxonomies = false # use showTaxonomies OR showCategoryOnly, not both
  showCategoryOnly = false # use showTaxonomies OR showCategoryOnly, not both
  showAuthorsBadges = false
  showWordCount = true
  # sharingLinks = [ "linkedin", "twitter", "bluesky", "mastodon", "reddit", "pinterest", "facebook", "email", "whatsapp", "telegram", "line"]
  showZenMode = false

# 文章页
[list]
  showHero = false
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false # 是否在标题栏显示面包屑导航
  showSummary = true # 是否在列表页显示文章摘要。如果在扉页参数中没有提供摘要，那么将会使用站点配置 中的 summaryLength 参数自动生成一个
  showTableOfContents = true # 是否在文章中显示目录表
  showCards = false 
  orderByWeight = false
  groupByYear = true # 是否根据年做聚合
  cardView = false # 将列表展示为卡片容器
  cardViewScreenWidth = false # 增强列表中卡片的宽度，使其可以占据可用的全部宽度
  constrainItemsWidth = false # 将项目宽度限制为 prose 以提高可读性。在没有 feature 图片的时候非常有用
  showViews = false # 需要配合firebase使用
  showLikes = false # 需要配合firebase使用

# 网站地图
[sitemap]
  excludedKinds = ["taxonomy", "term"]

# 分类法
[taxonomy]
  showTermCount = true # 是否在分类列表总显示对应的数量
  showHero = false # 缩略图是否会在每个页面中作为 hero 图像显示
  # heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false # 是否显示文章阅读量。这需要集成 firebase
  showLikes = false
  showTableOfContents = false # 是否显示目录
  cardView = false # 将列表展示为卡片容器

# 术语/词语/措辞
[term]
  showHero = false
  # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false

# Firebase(Firebase 平台)
[firebase]
  # apiKey = "XXXXXX"
  # authDomain = "XXXXXX"
  # projectId = "XXXXXX"
  # storageBucket = "XXXXXX"
  # messagingSenderId = "XXXXXX"
  # appId = "XXXXXX"
  # measurementId = "XXXXXX"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[umamiAnalytics]
  # websiteid = "ABC12345"
  # domain = "llama.yoursite.com"
  # dataDomains = "yoursite.com,yoursite2.com"
  # scriptName = ""
  # enableTrackEvent = true

[selineAnalytics]
  # token = "XXXXXX"
  # enableTrackEvent = true

[buymeacoffee]
  # identifier = ""
  # globalWidget = true
  # globalWidgetMessage = "Hello"
  # globalWidgetColor = "#FFDD00"
  # globalWidgetPosition = "right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
  # fediverse = ""

[rssnext]
  # feedId = ""
  # userId = ""

[advertisement]
  # adsense = ""
